version: '3'
services:

  mysql:
    image: mysql
    container_name: mysql_todolist_douglas
 
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - '3306:3306'
    volumes:
      - ./db/mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080